version: '2'
services:
  cli-content:
    container_name: cvedia-cli-content
    image: tianon/true
    volumes:
      - ../src:/var/www/cvedia-cli
  cvedia-cli:
    container_name: cvedia-cli
    build: cvedia-cli
    ports:
      - 0.0.0.0:81:80
      #-p IP:host_port:container_port
    depends_on:
      - cli-content
    container_name: cvedia-cli
    build: cvedia-cli
    volumes_from:
      - cli-content
